## Neural network to predict when to buy, sell or hold a stock

Here we are going to build a prediction algorithm to tell us when to buy, sell or hold a stock. This prediction task has been set up in such a way that the algorithm will make a buy/sell/hold prediction once every day. The data which we'll use are the historical prices of *Netflix* stock dating back to 2002. We'll build a sequential neural network using *Keras* and *Tensorflow*, as well as *Pandas* and *Numpy* for handling the data and doing some computtions.

### Import historical price data

Begin by loading all required packages

In [1]:
from bokeh.plotting import figure, output_notebook, show
from bokeh.models import ColumnDataSource
from bokeh.palettes import Spectral3
from bokeh.transform import factor_cmap
import bokeh.models as bmo
#
import pandas as pd
import numpy as np
#
from keras.layers import Input, Embedding, Dense, concatenate, Dropout, Flatten
from keras.models import Model, load_model
from keras import metrics, initializers, optimizers, regularizers

Using TensorFlow backend.


Import data using pandas and convert the columns to the appropriate data types.

In [2]:

pd.set_option("display.max_rows",10)
pd.set_option("display.max_columns",100)
NtflxData = pd.read_csv("NFLX.csv")
print("The data types in our table are:")
display(NtflxData.dtypes)
print ("### Changing index to 'date' ###")
NtflxData['Date'] = pd.to_datetime(NtflxData['Date'])
NtflxData = NtflxData.set_index('Date')
display(NtflxData)

The data types in our table are:


Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume       float64
dtype: object

### Changing index to 'date' ###


Open        High         Low       Close   Adj Close  \
Date                                                                     
2002-05-23    1.156429    1.242857    1.145714    1.196429    1.196429   
2002-05-24    1.214286    1.225000    1.197143    1.210000    1.210000   
2002-05-28    1.213571    1.232143    1.157143    1.157143    1.157143   
2002-05-29    1.164286    1.164286    1.085714    1.103571    1.103571   
2002-05-30    1.107857    1.107857    1.071429    1.071429    1.071429   
...                ...         ...         ...         ...         ...   
2018-02-01  266.410004  271.950012  263.380005  265.070007  265.070007   
2018-02-02  263.000000  270.619995  262.709991  267.429993  267.429993   
2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   

                 Volume  
Date                     
2002-05-23  104790000.0  
2002-05-24   11104800.0  
2002-05-28    6609400.0  
2002-05-29    6757800.0  
2002-05-30   10154200.0  
...                 ...  
2018-02-01    9669000.0  
2018-02-02    9123600.0  
2018-02-05   11896100.0  
2018-02-06   12595800.0  
2018-02-07    8705100.0  

[3958 rows x 6 columns]

We'll also import *S&P500* data to use as feature. The *S&P500* index should tell us the overall market trend, which might impact the our stock of interest.

*Note: We are actually using IVV index fund here because it mimicks the actual S&P500 index, and was easily obtainable.*

In [3]:
### import S&P 500 data
IVVData = pd.read_csv('IVV.csv')
IVVData['Date'] = pd.to_datetime(IVVData['Date'])
IVVData = IVVData.set_index('Date')
display(IVVData.head())

Open       High        Low      Close   Adj Close   Volume
Date                                                                       
2000-05-19  142.65625  142.65625  140.25000  140.68750  100.833214   775500
2000-05-22  140.59375  140.59375  136.81250  139.81250  100.206131  1850600
2000-05-23  140.21875  140.21875  137.68750  137.68750   98.683067   373900
2000-05-24  137.75000  140.06250  136.65625  139.75000  100.161354   400300
2000-05-25  140.03125  140.93750  137.87500  138.46875   99.243027    69600

#### Add some features

Some features extracted from the *date* will be added here. Additionally, we'll also add the *close price of next day* from which the exact *target* will be extracted.

In [4]:

NtflxData = NtflxData[pd.notnull(NtflxData['Close'])]
NtflxData['NextDayClose'] = np.nan
NtflxData['NextDayClose'][0:(len(NtflxData)-1)] = NtflxData['Close'][1:len(NtflxData)]
NtflxData['Day'] = NtflxData.index.day
NtflxData['Month'] = NtflxData.index.month
NtflxData['Year'] = NtflxData.index.year
NtflxData['DayofWeek'] = NtflxData.index.dayofweek
NtflxData['DayofYear'] = NtflxData.index.dayofyear
display(NtflxData)

#### Now for S&P 500

IVVData = IVVData[pd.notnull(IVVData['Close'])]
IVVData['NextDayClose'] = np.nan
IVVData['NextDayClose'][0:(len(IVVData)-1)] = IVVData['Close'][1:len(IVVData)]
IVVData['Day'] = IVVData.index.day
IVVData['Month'] = IVVData.index.month
IVVData['Year'] = IVVData.index.year
IVVData['DayofWeek'] = IVVData.index.dayofweek
IVVData['DayofYear'] = IVVData.index.dayofyear
display(IVVData)

Open        High         Low       Close   Adj Close  \
Date                                                                     
2002-05-23    1.156429    1.242857    1.145714    1.196429    1.196429   
2002-05-24    1.214286    1.225000    1.197143    1.210000    1.210000   
2002-05-28    1.213571    1.232143    1.157143    1.157143    1.157143   
2002-05-29    1.164286    1.164286    1.085714    1.103571    1.103571   
2002-05-30    1.107857    1.107857    1.071429    1.071429    1.071429   
...                ...         ...         ...         ...         ...   
2018-02-01  266.410004  271.950012  263.380005  265.070007  265.070007   
2018-02-02  263.000000  270.619995  262.709991  267.429993  267.429993   
2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   

                 Volume  NextDayClose  Day  Month  Year  DayofWeek  DayofYear  
Date                                                                           
2002-05-23  104790000.0      1.210000   23      5  2002          3        143  
2002-05-24   11104800.0      1.157143   24      5  2002          4        144  
2002-05-28    6609400.0      1.103571   28      5  2002          1        148  
2002-05-29    6757800.0      1.071429   29      5  2002          2        149  
2002-05-30   10154200.0      1.076429   30      5  2002          3        150  
...                 ...           ...  ...    ...   ...        ...        ...  
2018-02-01    9669000.0    267.429993    1      2  2018          3         32  
2018-02-02    9123600.0    254.259995    2      2  2018          4         33  
2018-02-05   11896100.0    265.720001    5      2  2018          0         36  
2018-02-06   12595800.0    264.559998    6      2  2018          1         37  
2018-02-07    8705100.0           NaN    7      2  2018          2         38  

[3956 rows x 12 columns]

/Users/shivakumar/anaconda/envs/GitHubRepos/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()


Open        High         Low       Close   Adj Close  \
Date                                                                     
2000-05-19  142.656250  142.656250  140.250000  140.687500  100.833214   
2000-05-22  140.593750  140.593750  136.812500  139.812500  100.206131   
2000-05-23  140.218750  140.218750  137.687500  137.687500   98.683067   
2000-05-24  137.750000  140.062500  136.656250  139.750000  100.161354   
2000-05-25  140.031250  140.937500  137.875000  138.468750   99.243027   
...                ...         ...         ...         ...         ...   
2018-02-12  265.670013  268.929993  263.820007  267.179993  267.179993   
2018-02-13  265.899994  268.559998  265.239990  267.959991  267.959991   
2018-02-14  266.359985  271.980011  266.220001  271.649994  271.649994   
2018-02-15  273.519989  275.029999  270.779999  275.019989  275.019989   
2018-02-16  274.359985  277.359985  274.230011  275.089996  275.089996   

             Volume  NextDayClose  Day  Month  Year  DayofWeek  DayofYear  
Date                                                                       
2000-05-19   775500    139.812500   19      5  2000          4        140  
2000-05-22  1850600    137.687500   22      5  2000          0        143  
2000-05-23   373900    139.750000   23      5  2000          1        144  
2000-05-24   400300    138.468750   24      5  2000          2        145  
2000-05-25    69600    137.843750   25      5  2000          3        146  
...             ...           ...  ...    ...   ...        ...        ...  
2018-02-12  6801400    267.959991   12      2  2018          0         43  
2018-02-13  4210500    271.649994   13      2  2018          1         44  
2018-02-14  6380400    275.019989   14      2  2018          2         45  
2018-02-15  5461700    275.089996   15      2  2018          3         46  
2018-02-16  4740000           NaN   16      2  2018          4         47  

[4465 rows x 12 columns]

Here the actual *target* feature will be extracted. Essentially, if the next day's *Percent Change in Closing Price* is larger than +1, then it is considered a strong *buy* signal. On the other hand, if it is less than -1, then it is considered a strong sell signal. Anything between -1 and +1 is considered a weak price movement for which the signal will be *hold*.

In [5]:
NtflxData['NextDayPrcntChange'] = (NtflxData['NextDayClose'] - NtflxData['Close']) / NtflxData['Close']
NtflxData['NextDayPrcntChangeBinned'] = np.zeros(len(NtflxData))
NtflxData['NextDayPrcntChangeBinned'][(NtflxData['NextDayPrcntChange'] > 0.01)] = 1
NtflxData['NextDayPrcntChangeBinned'][(NtflxData['NextDayPrcntChange'] < -0.01)] = -1
NtflxData['S.No.'] = range(len(NtflxData))
display(NtflxData)



/Users/shivakumar/anaconda/envs/GitHubRepos/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/shivakumar/anaconda/envs/GitHubRepos/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


Open        High         Low       Close   Adj Close  \
Date                                                                     
2002-05-23    1.156429    1.242857    1.145714    1.196429    1.196429   
2002-05-24    1.214286    1.225000    1.197143    1.210000    1.210000   
2002-05-28    1.213571    1.232143    1.157143    1.157143    1.157143   
2002-05-29    1.164286    1.164286    1.085714    1.103571    1.103571   
2002-05-30    1.107857    1.107857    1.071429    1.071429    1.071429   
...                ...         ...         ...         ...         ...   
2018-02-01  266.410004  271.950012  263.380005  265.070007  265.070007   
2018-02-02  263.000000  270.619995  262.709991  267.429993  267.429993   
2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   

                 Volume  NextDayClose  Day  Month  Year  DayofWeek  DayofYear  \
Date                                                                            
2002-05-23  104790000.0      1.210000   23      5  2002          3        143   
2002-05-24   11104800.0      1.157143   24      5  2002          4        144   
2002-05-28    6609400.0      1.103571   28      5  2002          1        148   
2002-05-29    6757800.0      1.071429   29      5  2002          2        149   
2002-05-30   10154200.0      1.076429   30      5  2002          3        150   
...                 ...           ...  ...    ...   ...        ...        ...   
2018-02-01    9669000.0    267.429993    1      2  2018          3         32   
2018-02-02    9123600.0    254.259995    2      2  2018          4         33   
2018-02-05   11896100.0    265.720001    5      2  2018          0         36   
2018-02-06   12595800.0    264.559998    6      2  2018          1         37   
2018-02-07    8705100.0           NaN    7      2  2018          2         38   

            NextDayPrcntChange  NextDayPrcntChangeBinned  S.No.  
Date                                                             
2002-05-23            0.011343                       1.0      0  
2002-05-24           -0.043683                      -1.0      1  
2002-05-28           -0.046297                      -1.0      2  
2002-05-29           -0.029125                      -1.0      3  
2002-05-30            0.004667                       0.0      4  
...                        ...                       ...    ...  
2018-02-01            0.008903                       0.0   3951  
2018-02-02           -0.049247                      -1.0   3952  
2018-02-05            0.045072                       1.0   3953  
2018-02-06           -0.004366                       0.0   3954  
2018-02-07                 NaN                       0.0   3955  

[3956 rows x 15 columns]

We'll now plot the *target* variable to make sure it is evenly spread throughout the table, as well as to make sure all the three possible target classes are equally represented.


In [6]:
output_notebook()
rolling_window_sum = NtflxData['NextDayPrcntChangeBinned'].rolling(7).sum()
line_data = {'x_values': rolling_window_sum.index,
        'y_values': rolling_window_sum.values}

source = ColumnDataSource(data=line_data)

line_plot = figure(plot_width=950, x_axis_type="datetime")
line_plot.line(x='x_values', y='y_values', source=source, line_width=3)
line_plot.xaxis.axis_label = 'Time'
line_plot.yaxis.axis_label = 'Window Sum of the Target Label'
show(line_plot)

Loading BokehJS ...

The above plot shows that all the three target classes are evenly distributed across the table. They do not trend up or down with respect to time (along x-axis).

It is also important to make sure the classes are balanced. The following plot shows that all the three target classes are approximately equaly represented. This would prevent the model from simply predicting the most frequent target class more often.

In [7]:
hist_data = NtflxData.groupby(by = 'NextDayPrcntChangeBinned').count().iloc[:,12]
hist_plot_data = {'Gain/Loss': ['Down', 'Neutral', 'High'], 'Count': NtflxData.groupby(by = 'NextDayPrcntChangeBinned').count().iloc[:,12].values}

source = ColumnDataSource(data=hist_plot_data)

hist_plot = figure(x_range=['Down', 'Neutral', 'High'], plot_width=550)
hist_plot.vbar(x='Gain/Loss', top='Count', source=source, width=0.3)

show(hist_plot)

The plot clearly shows that all the three target classes are almost eqaually represented.

Now we'll add *trend* features to know which way are the prices/market heading in the short as well as long term.

Add percent chnage in a given window.

In [8]:
ChangeDays = [1,2,3,5,7,14,30,60,90,120]
for CurrentDay in ChangeDays:
    NewColName = 'PCntChng{0}Days'.format(CurrentDay)
    NtflxData[NewColName] = NtflxData['Close'].pct_change(periods=CurrentDay)
    IVVData[NewColName] = IVVData['Close'].pct_change(periods=CurrentDay)

Add percent above/below rolling window mean

In [9]:
ChangeDays = [2,3,5,7,14,30,60,90,120]
for CurrentDay in ChangeDays:
    NewColName = 'CloseRolled{0}Day_DiffPer'.format(CurrentDay)
    NtflxData[NewColName] = (NtflxData['Close'] - NtflxData['Close'].rolling(window=CurrentDay).mean()) / NtflxData['Close'].rolling(window=CurrentDay).mean()
    IVVData[NewColName] = (IVVData['Close'] - IVVData['Close'].rolling(window=CurrentDay).mean()) / IVVData['Close'].rolling(window=CurrentDay).mean()

Add percent above/below rolling Volume mean

In [10]:
ChangeDays = [2,3,5,7,14,30]
for CurrentDay in ChangeDays:
    NewColName = 'VolumeRolled{0}Day_DiffPer'.format(CurrentDay)
    NtflxData[NewColName] = (NtflxData['Volume'] - NtflxData['Volume'].rolling(window=CurrentDay).mean()) / NtflxData['Volume'].rolling(window=CurrentDay).mean()
    IVVData[NewColName] = (IVVData['Volume'] - IVVData['Volume'].rolling(window=CurrentDay).mean()) / IVVData['Volume'].rolling(window=CurrentDay).mean()

In [11]:
display(NtflxData)
display(IVVData)

Open        High         Low       Close   Adj Close  \
Date                                                                     
2002-05-23    1.156429    1.242857    1.145714    1.196429    1.196429   
2002-05-24    1.214286    1.225000    1.197143    1.210000    1.210000   
2002-05-28    1.213571    1.232143    1.157143    1.157143    1.157143   
2002-05-29    1.164286    1.164286    1.085714    1.103571    1.103571   
2002-05-30    1.107857    1.107857    1.071429    1.071429    1.071429   
...                ...         ...         ...         ...         ...   
2018-02-01  266.410004  271.950012  263.380005  265.070007  265.070007   
2018-02-02  263.000000  270.619995  262.709991  267.429993  267.429993   
2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   

                 Volume  NextDayClose  Day  Month  Year  DayofWeek  DayofYear  \
Date                                                                            
2002-05-23  104790000.0      1.210000   23      5  2002          3        143   
2002-05-24   11104800.0      1.157143   24      5  2002          4        144   
2002-05-28    6609400.0      1.103571   28      5  2002          1        148   
2002-05-29    6757800.0      1.071429   29      5  2002          2        149   
2002-05-30   10154200.0      1.076429   30      5  2002          3        150   
...                 ...           ...  ...    ...   ...        ...        ...   
2018-02-01    9669000.0    267.429993    1      2  2018          3         32   
2018-02-02    9123600.0    254.259995    2      2  2018          4         33   
2018-02-05   11896100.0    265.720001    5      2  2018          0         36   
2018-02-06   12595800.0    264.559998    6      2  2018          1         37   
2018-02-07    8705100.0           NaN    7      2  2018          2         38   

            NextDayPrcntChange  NextDayPrcntChangeBinned  S.No.  \
Date                                                              
2002-05-23            0.011343                       1.0      0   
2002-05-24           -0.043683                      -1.0      1   
2002-05-28           -0.046297                      -1.0      2   
2002-05-29           -0.029125                      -1.0      3   
2002-05-30            0.004667                       0.0      4   
...                        ...                       ...    ...   
2018-02-01            0.008903                       0.0   3951   
2018-02-02           -0.049247                      -1.0   3952   
2018-02-05            0.045072                       1.0   3953   
2018-02-06           -0.004366                       0.0   3954   
2018-02-07                 NaN                       0.0   3955   

            PCntChng1Days  PCntChng2Days  PCntChng3Days  PCntChng5Days  \
Date                                                                     
2002-05-23            NaN            NaN            NaN            NaN   
2002-05-24       0.011343            NaN            NaN            NaN   
2002-05-28      -0.043683      -0.032836            NaN            NaN   
2002-05-29      -0.046297      -0.087958      -0.077613            NaN   
2002-05-30      -0.029125      -0.074074      -0.114521            NaN   
...                   ...            ...            ...            ...   
2018-02-01      -0.019349      -0.049247      -0.068590      -0.017167   
2018-02-02       0.008903      -0.010618      -0.040782      -0.026111   
2018-02-05      -0.049247      -0.040782      -0.059341      -0.106574   
2018-02-06       0.045072      -0.006394       0.002452      -0.046915   
2018-02-07      -0.004366       0.040510      -0.010732      -0.021236   

            PCntChng7Days  PCntChng14Days  PCntChng30Days  PCntChng60Days  \
Date                                                                        
2002-05-23  

Open        High         Low       Close   Adj Close  \
Date                                                                     
2000-05-19  142.656250  142.656250  140.250000  140.687500  100.833214   
2000-05-22  140.593750  140.593750  136.812500  139.812500  100.206131   
2000-05-23  140.218750  140.218750  137.687500  137.687500   98.683067   
2000-05-24  137.750000  140.062500  136.656250  139.750000  100.161354   
2000-05-25  140.031250  140.937500  137.875000  138.468750   99.243027   
...                ...         ...         ...         ...         ...   
2018-02-12  265.670013  268.929993  263.820007  267.179993  267.179993   
2018-02-13  265.899994  268.559998  265.239990  267.959991  267.959991   
2018-02-14  266.359985  271.980011  266.220001  271.649994  271.649994   
2018-02-15  273.519989  275.029999  270.779999  275.019989  275.019989   
2018-02-16  274.359985  277.359985  274.230011  275.089996  275.089996   

             Volume  NextDayClose  Day  Month  Year  DayofWeek  DayofYear  \
Date                                                                        
2000-05-19   775500    139.812500   19      5  2000          4        140   
2000-05-22  1850600    137.687500   22      5  2000          0        143   
2000-05-23   373900    139.750000   23      5  2000          1        144   
2000-05-24   400300    138.468750   24      5  2000          2        145   
2000-05-25    69600    137.843750   25      5  2000          3        146   
...             ...           ...  ...    ...   ...        ...        ...   
2018-02-12  6801400    267.959991   12      2  2018          0         43   
2018-02-13  4210500    271.649994   13      2  2018          1         44   
2018-02-14  6380400    275.019989   14      2  2018          2         45   
2018-02-15  5461700    275.089996   15      2  2018          3         46   
2018-02-16  4740000           NaN   16      2  2018          4         47   

            PCntChng1Days  PCntChng2Days  PCntChng3Days  PCntChng5Days  \
Date                                                                     
2000-05-19            NaN            NaN            NaN            NaN   
2000-05-22      -0.006219            NaN            NaN            NaN   
2000-05-23      -0.015199      -0.021324            NaN            NaN   
2000-05-24       0.014980      -0.000447      -0.006664            NaN   
2000-05-25      -0.009168       0.005674      -0.009611            NaN   
...                   ...            ...            ...            ...   
2018-02-12       0.013312       0.029119      -0.008940       0.004247   
2018-02-13       0.002919       0.016270       0.032124      -0.012166   
2018-02-14       0.013771       0.016730       0.030265       0.007641   
2018-02-15       0.012406       0.026347       0.029343       0.059317   
2018-02-16       0.000255       0.012663       0.026608       0.043312   

            PCntChng7Days  PCntChng14Days  PCntChng30Days  PCntChng60Days  \
Date                                                                        
2000-05-19            NaN             NaN             NaN             NaN   
2000-05-22            NaN             NaN             NaN             NaN   
2000-05-23            NaN             NaN             NaN             NaN   
2000-05-24            NaN             NaN             NaN             NaN   
2000-05-25            NaN             NaN             NaN             NaN   
...                   ...             ...             ...             ...   
2018-02-12      -0.058529       -0.063807       -0.009674        0.029278   
2018-02-13      -0.034483       -0.060581       -0.003310        0.037881   
2018-02-14       0.021049       -0.048011        0.002954        0.043443   
2018-02-15       0.013861       -0.047253        0.009544        0.059277   
2018-02-16       0.020401       -0.040663        0.005446        0.057876   

            PCntChng90Days  PCntChng120Days  CloseRolled2Day_DiffPer  \
Date            

Here we'll scale and normalize the appropriate features to prepare them as inputs to our model.

In [12]:
CategoricalFeatures = NtflxData.columns[[8,9,10]]
for CurrentColumn in CategoricalFeatures:
    NtflxData[CurrentColumn] = NtflxData[CurrentColumn].astype('category')
    NtflxData[CurrentColumn] = NtflxData[CurrentColumn].cat.codes
    IVVData[CurrentColumn] = IVVData[CurrentColumn].astype('category')
    IVVData[CurrentColumn] = IVVData[CurrentColumn].cat.codes


### Normalize Volume #####

NtflxData['Volume'] = np.log1p(NtflxData['Volume'])
NtflxData['Volume'] = (NtflxData['Volume'] - np.min(NtflxData['Volume'])) / (np.max(NtflxData['Volume'] - np.min(NtflxData['Volume'])))

IVVData['Volume'] = np.log1p(IVVData['Volume'])
IVVData['Volume'] = (IVVData['Volume'] - np.min(IVVData['Volume'])) / (np.max(IVVData['Volume'] - np.min(IVVData['Volume'])))

display (NtflxData)
display (IVVData)

Open        High         Low       Close   Adj Close  \
Date                                                                     
2002-05-23    1.156429    1.242857    1.145714    1.196429    1.196429   
2002-05-24    1.214286    1.225000    1.197143    1.210000    1.210000   
2002-05-28    1.213571    1.232143    1.157143    1.157143    1.157143   
2002-05-29    1.164286    1.164286    1.085714    1.103571    1.103571   
2002-05-30    1.107857    1.107857    1.071429    1.071429    1.071429   
...                ...         ...         ...         ...         ...   
2018-02-01  266.410004  271.950012  263.380005  265.070007  265.070007   
2018-02-02  263.000000  270.619995  262.709991  267.429993  267.429993   
2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   

              Volume  NextDayClose  Day  Month  Year  DayofWeek  DayofYear  \
Date                                                                         
2002-05-23  0.839738      1.210000   23      4     0          3        143   
2002-05-24  0.520547      1.157143   24      4     0          4        144   
2002-05-28  0.446759      1.103571   28      4     0          1        148   
2002-05-29  0.449917      1.071429   29      4     0          2        149   
2002-05-30  0.507821      1.076429   30      4     0          3        150   
...              ...           ...  ...    ...   ...        ...        ...   
2018-02-01  0.500859    267.429993    1      1    16          3         32   
2018-02-02  0.492602    254.259995    2      1    16          4         33   
2018-02-05  0.530336    265.720001    5      1    16          0         36   
2018-02-06  0.538463    264.559998    6      1    16          1         37   
2018-02-07  0.485925           NaN    7      1    16          2         38   

            NextDayPrcntChange  NextDayPrcntChangeBinned  S.No.  \
Date                                                              
2002-05-23            0.011343                       1.0      0   
2002-05-24           -0.043683                      -1.0      1   
2002-05-28           -0.046297                      -1.0      2   
2002-05-29           -0.029125                      -1.0      3   
2002-05-30            0.004667                       0.0      4   
...                        ...                       ...    ...   
2018-02-01            0.008903                       0.0   3951   
2018-02-02           -0.049247                      -1.0   3952   
2018-02-05            0.045072                       1.0   3953   
2018-02-06           -0.004366                       0.0   3954   
2018-02-07                 NaN                       0.0   3955   

            PCntChng1Days  PCntChng2Days  PCntChng3Days  PCntChng5Days  \
Date                                                                     
2002-05-23            NaN            NaN            NaN            NaN   
2002-05-24       0.011343            NaN            NaN            NaN   
2002-05-28      -0.043683      -0.032836            NaN            NaN   
2002-05-29      -0.046297      -0.087958      -0.077613            NaN   
2002-05-30      -0.029125      -0.074074      -0.114521            NaN   
...                   ...            ...            ...            ...   
2018-02-01      -0.019349      -0.049247      -0.068590      -0.017167   
2018-02-02       0.008903      -0.010618      -0.040782      -0.026111   
2018-02-05      -0.049247      -0.040782      -0.059341      -0.106574   
2018-02-06       0.045072      -0.006394       0.002452      -0.046915   
2018-02-07      -0.004366       0.040510      -0.010732      -0.021236   

            PCntChng7Days  PCntChng14Days  PCntChng30Days  PCntChng60Days  \
Date                                                                        
2002-05-23            NaN             NaN          

Open        High         Low       Close   Adj Close  \
Date                                                                     
2000-05-19  142.656250  142.656250  140.250000  140.687500  100.833214   
2000-05-22  140.593750  140.593750  136.812500  139.812500  100.206131   
2000-05-23  140.218750  140.218750  137.687500  137.687500   98.683067   
2000-05-24  137.750000  140.062500  136.656250  139.750000  100.161354   
2000-05-25  140.031250  140.937500  137.875000  138.468750   99.243027   
...                ...         ...         ...         ...         ...   
2018-02-12  265.670013  268.929993  263.820007  267.179993  267.179993   
2018-02-13  265.899994  268.559998  265.239990  267.959991  267.959991   
2018-02-14  266.359985  271.980011  266.220001  271.649994  271.649994   
2018-02-15  273.519989  275.029999  270.779999  275.019989  275.019989   
2018-02-16  274.359985  277.359985  274.230011  275.089996  275.089996   

              Volume  NextDayClose  Day  Month  Year  DayofWeek  DayofYear  \
Date                                                                         
2000-05-19  0.550053    139.812500   19      4     0          4        140   
2000-05-22  0.650107    137.687500   22      4     0          0        143   
2000-05-23  0.466132    139.750000   23      4     0          1        144   
2000-05-24  0.473980    138.468750   24      4     0          2        145   
2000-05-25  0.272731    137.843750   25      4     0          3        146   
...              ...           ...  ...    ...   ...        ...        ...   
2018-02-12  0.799841    267.959991   12      1    18          0         43   
2018-02-13  0.744675    271.649994   13      1    18          1         44   
2018-02-14  0.792490    275.019989   14      1    18          2         45   
2018-02-15  0.774605    275.089996   15      1    18          3         46   
2018-02-16  0.758302           NaN   16      1    18          4         47   

            PCntChng1Days  PCntChng2Days  PCntChng3Days  PCntChng5Days  \
Date                                                                     
2000-05-19            NaN            NaN            NaN            NaN   
2000-05-22      -0.006219            NaN            NaN            NaN   
2000-05-23      -0.015199      -0.021324            NaN            NaN   
2000-05-24       0.014980      -0.000447      -0.006664            NaN   
2000-05-25      -0.009168       0.005674      -0.009611            NaN   
...                   ...            ...            ...            ...   
2018-02-12       0.013312       0.029119      -0.008940       0.004247   
2018-02-13       0.002919       0.016270       0.032124      -0.012166   
2018-02-14       0.013771       0.016730       0.030265       0.007641   
2018-02-15       0.012406       0.026347       0.029343       0.059317   
2018-02-16       0.000255       0.012663       0.026608       0.043312   

            PCntChng7Days  PCntChng14Days  PCntChng30Days  PCntChng60Days  \
Date                                                                        
2000-05-19            NaN             NaN             NaN             NaN   
2000-05-22            NaN             NaN             NaN             NaN   
2000-05-23            NaN             NaN             NaN             NaN   
2000-05-24            NaN             NaN             NaN             NaN   
2000-05-25            NaN             NaN             NaN             NaN   
...                   ...             ...             ...             ...   
2018-02-12      -0.058529       -0.063807       -0.009674        0.029278   
2018-02-13      -0.034483       -0.060581       -0.003310        0.037881   
2018-02-14       0.021049       -0.048011        0.002954        0.043443   
2018-02-15       0.013861       -0.047253        0.009544        0.059277   
2018-02-16       0.020401       -0.040663        0.005446        0.057876   

            PCntChng90Days  PCntChng120Days  CloseRolled2Day_DiffPer  \
Dat

Now we need to merge the two dataframes, *Netflix* and *S&P500*.

In [13]:
CombinedDF = NtflxData.join(IVVData[['PCntChng1Days','PCntChng2Days','PCntChng3Days','PCntChng5Days',
                                     'PCntChng7Days','PCntChng14Days','PCntChng30Days','PCntChng60Days',
                                     'PCntChng90Days','PCntChng120Days','CloseRolled2Day_DiffPer',
                                     'CloseRolled3Day_DiffPer','CloseRolled5Day_DiffPer','CloseRolled7Day_DiffPer',
                                     'CloseRolled14Day_DiffPer','CloseRolled30Day_DiffPer']],
                            lsuffix='_Ntflx', rsuffix='_SP500')
display(CombinedDF)

Open        High         Low       Close   Adj Close  \
Date                                                                     
2002-05-23    1.156429    1.242857    1.145714    1.196429    1.196429   
2002-05-24    1.214286    1.225000    1.197143    1.210000    1.210000   
2002-05-28    1.213571    1.232143    1.157143    1.157143    1.157143   
2002-05-29    1.164286    1.164286    1.085714    1.103571    1.103571   
2002-05-30    1.107857    1.107857    1.071429    1.071429    1.071429   
...                ...         ...         ...         ...         ...   
2018-02-01  266.410004  271.950012  263.380005  265.070007  265.070007   
2018-02-02  263.000000  270.619995  262.709991  267.429993  267.429993   
2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   

              Volume  NextDayClose  Day  Month  Year  DayofWeek  DayofYear  \
Date                                                                         
2002-05-23  0.839738      1.210000   23      4     0          3        143   
2002-05-24  0.520547      1.157143   24      4     0          4        144   
2002-05-28  0.446759      1.103571   28      4     0          1        148   
2002-05-29  0.449917      1.071429   29      4     0          2        149   
2002-05-30  0.507821      1.076429   30      4     0          3        150   
...              ...           ...  ...    ...   ...        ...        ...   
2018-02-01  0.500859    267.429993    1      1    16          3         32   
2018-02-02  0.492602    254.259995    2      1    16          4         33   
2018-02-05  0.530336    265.720001    5      1    16          0         36   
2018-02-06  0.538463    264.559998    6      1    16          1         37   
2018-02-07  0.485925           NaN    7      1    16          2         38   

            NextDayPrcntChange  NextDayPrcntChangeBinned  S.No.  \
Date                                                              
2002-05-23            0.011343                       1.0      0   
2002-05-24           -0.043683                      -1.0      1   
2002-05-28           -0.046297                      -1.0      2   
2002-05-29           -0.029125                      -1.0      3   
2002-05-30            0.004667                       0.0      4   
...                        ...                       ...    ...   
2018-02-01            0.008903                       0.0   3951   
2018-02-02           -0.049247                      -1.0   3952   
2018-02-05            0.045072                       1.0   3953   
2018-02-06           -0.004366                       0.0   3954   
2018-02-07                 NaN                       0.0   3955   

            PCntChng1Days_Ntflx  PCntChng2Days_Ntflx  PCntChng3Days_Ntflx  \
Date                                                                        
2002-05-23                  NaN                  NaN                  NaN   
2002-05-24             0.011343                  NaN                  NaN   
2002-05-28            -0.043683            -0.032836                  NaN   
2002-05-29            -0.046297            -0.087958            -0.077613   
2002-05-30            -0.029125            -0.074074            -0.114521   
...                         ...                  ...                  ...   
2018-02-01            -0.019349            -0.049247            -0.068590   
2018-02-02             0.008903            -0.010618            -0.040782   
2018-02-05            -0.049247            -0.040782            -0.059341   
2018-02-06             0.045072            -0.006394             0.002452   
2018-02-07            -0.004366             0.040510            -0.010732   

            PCntChng5Days_Ntflx  PCntChng7Days_Ntflx  PCntChng14Days_Ntflx  \
Date                                                                         
2002-05-23

### Build model

Now we are ready to start building our model.

But first, we'll remove *NANs* from the dataframe to prevent difficulties later. Then we'll split the entire data randomly into *Training* and *Testing* data.

In [14]:
for CurrentColumn in CombinedDF.columns:
    RowsWithNAN = ~np.isnan(CombinedDF[CurrentColumn])
    CombinedDF = CombinedDF[RowsWithNAN]

    TrainIndices = np.random.randint(low=0, high = int(len(CombinedDF)), size = round(0.2*int(len(CombinedDF))))
TrainIndicesBoolean = pd.Series(range(len(CombinedDF)), copy=True).isin(TrainIndices)
MyTest = pd.DataFrame(CombinedDF[TrainIndicesBoolean.values], copy=True)
TrainIndicesBoolean = ~pd.Series(range(len(CombinedDF)), copy=True).isin(TrainIndices)
MyTrain = pd.DataFrame(CombinedDF[TrainIndicesBoolean.values], copy=True)
pd.options.display.max_columns = None
display(MyTrain)
display(MyTest)

Open        High         Low       Close   Adj Close  \
Date                                                                     
2002-11-12    0.600000    0.614286    0.572143    0.577857    0.577857   
2002-11-13    0.579286    0.642857    0.555714    0.641429    0.641429   
2002-11-14    0.642857    0.645000    0.618571    0.618571    0.618571   
2002-11-15    0.642143    0.653571    0.589286    0.650000    0.650000   
2002-11-18    0.648571    0.780714    0.625000    0.778571    0.778571   
...                ...         ...         ...         ...         ...   
2018-01-31  281.940002  282.290009  269.579987  270.299988  270.299988   
2018-02-01  266.410004  271.950012  263.380005  265.070007  265.070007   
2018-02-02  263.000000  270.619995  262.709991  267.429993  267.429993   
2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   

              Volume  NextDayClose  Day  Month  Year  DayofWeek  DayofYear  \
Date                                                                         
2002-11-12  0.289746      0.641429   12     10     0          1        316   
2002-11-13  0.344992      0.618571   13     10     0          2        317   
2002-11-14  0.168039      0.650000   14     10     0          3        318   
2002-11-15  0.279967      0.778571   15     10     0          4        319   
2002-11-18  0.506521      0.664286   18     10     0          0        322   
...              ...           ...  ...    ...   ...        ...        ...   
2018-01-31  0.527912    265.070007   31      0    16          2         31   
2018-02-01  0.500859    267.429993    1      1    16          3         32   
2018-02-02  0.492602    254.259995    2      1    16          4         33   
2018-02-05  0.530336    265.720001    5      1    16          0         36   
2018-02-06  0.538463    264.559998    6      1    16          1         37   

            NextDayPrcntChange  NextDayPrcntChangeBinned  S.No.  \
Date                                                              
2002-11-12            0.110013                       1.0    120   
2002-11-13           -0.035636                      -1.0    121   
2002-11-14            0.050809                       1.0    122   
2002-11-15            0.197802                       1.0    123   
2002-11-18           -0.146788                      -1.0    124   
...                        ...                       ...    ...   
2018-01-31           -0.019349                      -1.0   3950   
2018-02-01            0.008903                       0.0   3951   
2018-02-02           -0.049247                      -1.0   3952   
2018-02-05            0.045072                       1.0   3953   
2018-02-06           -0.004366                       0.0   3954   

            PCntChng1Days_Ntflx  PCntChng2Days_Ntflx  PCntChng3Days_Ntflx  \
Date                                                                        
2002-11-12            -0.038050            -0.053801            -0.025301   
2002-11-13             0.110013             0.067778             0.050294   
2002-11-14            -0.035636             0.070457             0.029726   
2002-11-15             0.050809             0.013362             0.124846   
2002-11-18             0.197802             0.258661             0.213807   
...                         ...                  ...                  ...   
2018-01-31            -0.030488            -0.050213            -0.015659   
2018-02-01            -0.019349            -0.049247            -0.068590   
2018-02-02             0.008903            -0.010618            -0.040782   
2018-02-05            -0.049247            -0.040782            -0.059341   
2018-02-06             0.045072            -0.006394             0.002452   

            PCntChng5Days_Ntflx  PCntChng7Days_Ntflx  PCntChng14Days_Ntflx  \
Date                                                                         
2002-11-12

Open        High         Low       Close   Adj Close  \
Date                                                                     
2002-11-20    0.674286    0.727857    0.660714    0.717143    0.717143   
2002-11-25    0.792857    0.796429    0.753571    0.792857    0.792857   
2002-12-02    0.742857    0.796429    0.724286    0.761429    0.761429   
2002-12-03    0.750000    0.789286    0.739286    0.770714    0.770714   
2002-12-12    0.905714    0.914286    0.885714    0.900714    0.900714   
...                ...         ...         ...         ...         ...   
2017-12-29  192.509995  193.949997  191.220001  191.960007  191.960007   
2018-01-11  214.289993  217.750000  213.350006  217.240005  217.240005   
2018-01-19  222.750000  223.490005  218.500000  220.460007  220.460007   
2018-01-22  222.000000  227.789993  221.199997  227.580002  227.580002   
2018-01-30  277.000000  282.730011  272.700012  278.799988  278.799988   

              Volume  NextDayClose  Day  Month  Year  DayofWeek  DayofYear  \
Date                                                                         
2002-11-20  0.506857      0.785714   20     10     0          2        324   
2002-11-25  0.400415      0.749286   25     10     0          0        329   
2002-12-02  0.277413      0.770714    2     11     0          0        336   
2002-12-03  0.199899      0.710000    3     11     0          1        337   
2002-12-12  0.310428      0.892857   12     11     0          3        346   
...              ...           ...  ...    ...   ...        ...        ...   
2017-12-29  0.412314    201.070007   29     11    15          4        363   
2018-01-11  0.467728    221.229996   11      0    16          3         11   
2018-01-19  0.513240    227.580002   19      0    16          4         19   
2018-01-22  0.586868    250.289993   22      0    16          0         22   
2018-01-30  0.537183    270.299988   30      0    16          1         30   

            NextDayPrcntChange  NextDayPrcntChangeBinned  S.No.  \
Date                                                              
2002-11-20            0.095617                       1.0    126   
2002-11-25           -0.054954                      -1.0    129   
2002-12-02            0.012194                       1.0    133   
2002-12-03           -0.078776                      -1.0    134   
2002-12-12           -0.008723                       0.0    141   
...                        ...                       ...    ...   
2017-12-29            0.047458                       1.0   3929   
2018-01-11            0.018367                       1.0   3937   
2018-01-19            0.032296                       1.0   3942   
2018-01-22            0.099789                       1.0   3943   
2018-01-30           -0.030488                      -1.0   3949   

            PCntChng1Days_Ntflx  PCntChng2Days_Ntflx  PCntChng3Days_Ntflx  \
Date                                                                        
2002-11-20             0.079570            -0.078898             0.103297   
2002-11-25             0.008174             0.009091             0.105577   
2002-12-02            -0.017511             0.013308             0.016206   
2002-12-03             0.012194            -0.005530             0.025664   
2002-12-12             0.003980             0.033606             0.126898   
...                         ...                  ...                  ...   
2017-12-29            -0.003892             0.030713             0.022369   
2018-01-11             0.022210             0.037886             0.024475   
2018-01-19             0.000590             0.013609            -0.004830   
2018-01-22             0.032296             0.032905             0.046345   
2018-01-30            -0.020345             0.015295             0.033741   

            PCntChng5Days_Ntflx  PCntChng7Days_Ntflx  PCntChng14Days_Ntflx  \
Date                                                                         
2002-11-20

Just printing out the columns here to cross-check their position in the data frame.

In [15]:
pd.set_option("display.max_rows",100)
pd.DataFrame(MyTrain.columns,range(len(MyTrain.columns)))

0
0                             Open
1                             High
2                              Low
3                            Close
4                        Adj Close
5                           Volume
6                     NextDayClose
7                              Day
8                            Month
9                             Year
10                       DayofWeek
11                       DayofYear
12              NextDayPrcntChange
13        NextDayPrcntChangeBinned
14                           S.No.
15             PCntChng1Days_Ntflx
16             PCntChng2Days_Ntflx
17             PCntChng3Days_Ntflx
18             PCntChng5Days_Ntflx
19             PCntChng7Days_Ntflx
20            PCntChng14Days_Ntflx
21            PCntChng30Days_Ntflx
22            PCntChng60Days_Ntflx
23            PCntChng90Days_Ntflx
24           PCntChng120Days_Ntflx
25   CloseRolled2Day_DiffPer_Ntflx
26   CloseRolled3Day_DiffPer_Ntflx
27   CloseRolled5Day_DiffPer_Ntflx
28   CloseRolled7Day_DiffPer_Ntflx
29  CloseRolled14Day_DiffPer_Ntflx
30  CloseRolled30Day_DiffPer_Ntflx
31        CloseRolled60Day_DiffPer
32        CloseRolled90Day_DiffPer
33       CloseRolled120Day_DiffPer
34        VolumeRolled2Day_DiffPer
35        VolumeRolled3Day_DiffPer
36        VolumeRolled5Day_DiffPer
37        VolumeRolled7Day_DiffPer
38       VolumeRolled14Day_DiffPer
39       VolumeRolled30Day_DiffPer
40             PCntChng1Days_SP500
41             PCntChng2Days_SP500
42             PCntChng3Days_SP500
43             PCntChng5Days_SP500
44             PCntChng7Days_SP500
45            PCntChng14Days_SP500
46            PCntChng30Days_SP500
47            PCntChng60Days_SP500
48            PCntChng90Days_SP500
49           PCntChng120Days_SP500
50   CloseRolled2Day_DiffPer_SP500
51   CloseRolled3Day_DiffPer_SP500
52   CloseRolled5Day_DiffPer_SP500
53   CloseRolled7Day_DiffPer_SP500
54  CloseRolled14Day_DiffPer_SP500
55  CloseRolled30Day_DiffPer_SP500

Now will be the important part where we'll prepare the inputs and make sure the input arrays have the right shape, as expected by *Keras* and *Tensorflow* based on our model.

In [80]:
MonthCodeInput = MyTrain['Month']
MonthCodeInput = np.array(MonthCodeInput.astype('int32'))
MonthCodeInput = np.reshape (MonthCodeInput,(-1,1))
print ('Month Code Input')
print (MonthCodeInput[:10])

YearCodeInput = MyTrain['Year']
YearCodeInput = np.array(YearCodeInput.astype('int32'))
YearCodeInput = np.reshape (YearCodeInput,(-1,1))
print ('Year Code Input')
print (YearCodeInput)
print (YearCodeInput[:10])

DayOfWeekCodeInput = MyTrain['DayofWeek']
DayOfWeekCodeInput = np.array(DayOfWeekCodeInput.astype('int32'))
DayOfWeekCodeInput = np.reshape (DayOfWeekCodeInput,(-1,1))
print ('Day of Week')
print (DayOfWeekCodeInput[:10])

#########################

ContFeaturesColumns = list([5,7,11]) + list(range(15, 18)) + list(range(25,35)) + list(range(35,37))+ list(range(40,43)) + list(range(50,53))
ContinuousFeatures = MyTrain.columns[ContFeaturesColumns]
ContinuousInput = MyTrain[ContinuousFeatures]
ContinuousInput = np.array(ContinuousInput)
ContinuousInput = np.asarray(ContinuousInput, dtype=np.float32)
ContinuousInput = np.reshape(ContinuousInput,(-1,len(ContinuousFeatures)))
print ('Continuous Input')
print(ContinuousInput[:3])



##### Gain/Loss One Hot Encode #####
print("Gain-Loss binned")
#print(MyTrain['NextDayPrcntChangeBinned'][:10])
GainLossOutput = pd.Series(list(np.reshape(MyTrain['NextDayPrcntChangeBinned'],-1)))
GainLossOutputCodes = pd.get_dummies(GainLossOutput)
GainLossOutputCodes = np.array(GainLossOutputCodes)
print ('Gain loss one hot codes')
print (GainLossOutputCodes[:10])


Month Code Input
[[10]
 [10]
 [10]
 [10]
 [10]
 [10]
 [10]
 [10]
 [10]
 [10]]
Year Code Input
[[ 0]
 [ 0]
 [ 0]
 ...
 [16]
 [16]
 [16]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
Day of Week
[[1]
 [2]
 [3]
 [4]
 [0]
 [1]
 [3]
 [4]
 [1]
 [2]]
Continuous Input
[[ 2.89745629e-01  1.20000000e+01  3.16000000e+02 -3.80497202e-02
  -5.38009591e-02 -2.53012106e-02 -1.93938259e-02 -3.11375782e-02
  -4.05598283e-02 -6.67438656e-02 -8.27666670e-02  9.10538435e-03
  -1.91000178e-01 -2.79016286e-01 -3.35673839e-01  7.10382521e-01
  -1.21773288e-01 -3.59446615e-01  6.23091683e-03 -9.14769061e-03
  -1.99712794e-02  3.10578244e-03 -1.01224461e-03 -1.35495095e-02]
 [ 3.44991684e-01  1.30000000e+01  3.17000000e+02  1.10013381e-01
   6.77776784e-02  5.02935909e-02  5.21387123e-02  5.73005490e-02
   6.07143007e-02  4.31469940e-02  1.10179493e-02  1.16036959e-01
  -9.55628008e-02 -1.93895340e-01 -2.58550316e-01  1.91840947e-01
   6.73272133e-01  2.14608982e-01 -2.13919161e-03  4.07839613e-03
  -1.1

Now we'll build our model.

In [43]:
month_input = Input(shape=(1,), dtype='int32', name='month_input')
year_input = Input(shape = (1,), dtype='int32', name = 'year_input')
dayofweek_input = Input(shape = (1,), dtype='int32', name = 'dayofweek_input')


Month_x = Embedding(output_dim=2, input_dim=(MonthCodeInput.max()+1), input_length=1)(month_input)
Month_x = Flatten()(Month_x)
Year_x = Embedding(output_dim=2, input_dim=(YearCodeInput.max()+1), input_length=1)(year_input)
Year_x = Flatten()(Year_x)
DayOfWeek_x = Embedding(output_dim=(DayOfWeekCodeInput.max()+1), input_dim=(DayOfWeekCodeInput.max()+1), 
                        input_length=1)(dayofweek_input)
DayOfWeek_x = Flatten()(DayOfWeek_x)

continuous_input = Input(shape=(len(ContinuousFeatures),), dtype='float32', name='cont_input')



x_Concat = concatenate([DayOfWeek_x, continuous_input])


x_Concat = Dense(10, activation='sigmoid')(x_Concat)

x_Concat = Dense(10, activation='sigmoid')(x_Concat)


main_output = Dense(3, name='main_output', activation = 'softmax')(x_Concat)


model = Model(inputs=[month_input, year_input, dayofweek_input, continuous_input], outputs = [main_output])   


In [44]:
display(model.summary())

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
dayofweek_input (InputLayer)    (None, 1)            0                                            
__________________________________________________________________________________________________
embedding_15 (Embedding)        (None, 1, 5)         25          dayofweek_input[0][0]            
__________________________________________________________________________________________________
flatten_15 (Flatten)            (None, 5)            0           embedding_15[0][0]               
__________________________________________________________________________________________________
cont_input (InputLayer)         (None, 24)           0                                            
__________________________________________________________________________________________________
concatenat

None

### Train the model

In [45]:
model.compile(optimizer='adadelta',
              loss={'main_output': 'categorical_crossentropy'}, metrics=['accuracy'])
history = model.fit({'month_input': MonthCodeInput, 'year_input': YearCodeInput, 
                     'dayofweek_input': DayOfWeekCodeInput, 'cont_input': ContinuousInput},
          {'main_output': GainLossOutputCodes},
         epochs=5, batch_size=1, verbose=1, validation_split=0.2, shuffle = True)

Train on 2510 samples, validate on 628 samples
Epoch 1/5
2510/2510 [==============================] - 11s 4ms/step - loss: 1.1050 - acc: 0.3486 - val_loss: 1.1109 - val_acc: 0.2914
Epoch 2/5
2510/2510 [==============================] - 10s 4ms/step - loss: 1.1002 - acc: 0.3378 - val_loss: 1.1065 - val_acc: 0.2914
Epoch 3/5
2510/2510 [==============================] - 10s 4ms/step - loss: 1.1020 - acc: 0.3339 - val_loss: 1.0999 - val_acc: 0.2468
Epoch 4/5
2510/2510 [==============================] - 10s 4ms/step - loss: 1.1014 - acc: 0.3319 - val_loss: 1.0979 - val_acc: 0.2914
Epoch 5/5
2510/2510 [==============================] - 10s 4ms/step - loss: 1.1009 - acc: 0.3426 - val_loss: 1.1116 - val_acc: 0.2914


### Generate Test features

In [79]:
MonthCodeInput_Test = MyTest['Month']
MonthCodeInput_Test = np.array(MonthCodeInput_Test.astype('int32'))
MonthCodeInput_Test = np.reshape (MonthCodeInput_Test,(-1,1))
print ('Month Code Input')
print (MonthCodeInput_Test[:10])

YearCodeInput_Test = MyTest['Year']
YearCodeInput_Test = np.array(YearCodeInput_Test.astype('int32'))
YearCodeInput_Test = np.reshape (YearCodeInput_Test,(-1,1))
print ('Year Code Input')
print (YearCodeInput_Test[:10])

DayOfWeekCodeInput_Test = MyTest['DayofWeek']
DayOfWeekCodeInput_Test = np.array(DayOfWeekCodeInput_Test.astype('int32'))
DayOfWeekCodeInput_Test = np.reshape (DayOfWeekCodeInput_Test,(-1,1))
print ('Day of Week')
print (DayOfWeekCodeInput_Test[:10])

#########################

ContinuousFeatures_Test = MyTest.columns[ContFeaturesColumns]
ContinuousInput_Test = MyTest[ContinuousFeatures_Test]
ContinuousInput_Test = np.array(ContinuousInput_Test)
ContinuousInput_Test = np.asarray(ContinuousInput_Test, dtype=np.float32)
ContinuousInput_Test = np.reshape(ContinuousInput_Test,(-1,len(ContinuousFeatures_Test)))
print ('Continuous Input')
print(ContinuousInput_Test[:3])


Month Code Input
[[10]
 [10]
 [11]
 [11]
 [11]
 [11]
 [ 0]
 [ 0]
 [ 1]
 [ 1]]
Year Code Input
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]
Day of Week
[[2]
 [0]
 [0]
 [1]
 [3]
 [2]
 [4]
 [4]
 [2]
 [0]]
Continuous Input
[[ 5.06857395e-01  2.00000000e+01  3.24000000e+02  7.95696452e-02
  -7.88983926e-02  1.03296921e-01  3.82625535e-02 -3.96805536e-03
   4.58336733e-02  8.00678656e-02  1.10268801e-01  1.63293839e-01
   4.45459783e-02 -6.63937256e-02 -1.53843284e-01 -4.73064393e-01
  -3.74109477e-01 -1.73505023e-02  1.22855678e-02  9.93817393e-03
   0.00000000e+00  6.10528048e-03  7.37967482e-03  5.89503348e-03]
 [ 4.00415301e-01  2.50000000e+01  3.29000000e+02  8.17365572e-03
   9.09109414e-03  1.05577268e-01  4.07019397e-03  5.73826628e-03
   5.81503063e-02  7.24635720e-02  1.75047114e-01  2.29371741e-01
   1.64416879e-01  4.78396192e-02 -5.44475354e-02  3.00740525e-02
  -2.76381910e-01 -5.89120388e-01  3.20575968e-03 -2.97373603e-03
   2.64596324e-02  1.60031475e-03  7.09750748e-0

Model will now be used to make predictions on the *Test* features.

In [47]:
PredictedValues = model.predict({'month_input': MonthCodeInput_Test, 'year_input': YearCodeInput_Test,
                                 'dayofweek_input': DayOfWeekCodeInput_Test, 'cont_input': ContinuousInput_Test},
          batch_size=100)
print(PredictedValues)

[[0.3210102  0.31155545 0.36743438]
 [0.3210102  0.31155545 0.36743438]
 [0.32101014 0.31155542 0.36743438]
 ...
 [0.31705022 0.2916461  0.39130366]
 [0.3166138  0.29038483 0.39300138]
 [0.31633314 0.28956643 0.3941004 ]]


Create a new dataframe to store the predicted and actual values.

In [75]:
PredictedValues_DF = pd.DataFrame(PredictedValues)
PredictedValues_DF.columns = ['PredictedValue_-1', 'PredictedValue_0', 'PredictedValue_+1']
PredictedValues_DF['S.No'] = range(len(MyTest))
PredictedValues_DF['ActualValues'] = np.array(MyTest['NextDayPrcntChangeBinned'])
PredictedValues_DF['NextDayPrcntChange'] = np.array(50*(abs(MyTest['NextDayPrcntChange'])))
display(PredictedValues_DF.head())

PredictedValue_-1  PredictedValue_0  PredictedValue_+1  S.No  ActualValues  \
0            0.32101          0.311555           0.367434     0           1.0   
1            0.32101          0.311555           0.367434     1          -1.0   
2            0.32101          0.311555           0.367434     2           1.0   
3            0.32101          0.311555           0.367434     3          -1.0   
4            0.32101          0.311555           0.367434     4           0.0   

   NextDayPrcntChange  
0            4.780846  
1            2.747721  
2            0.609709  
3            3.938815  
4            0.436154

In [76]:
print (PredictedValues_DF['ActualValues'].values[:10])

[ 1. -1.  1. -1.  0. -1.  1. -1. -1.  1.]


In [74]:
output_notebook()
circle_plot_data = {'x_values': PredictedValues_DF['S.No'], 'y_values': PredictedValues_DF['PredictedValue_+1'], 'size': PredictedValues_DF['NextDayPrcntChange']+3,
                   'circle_color': [str(x) for x in PredictedValues_DF['ActualValues'].values]}
source = ColumnDataSource(data=circle_plot_data)

circle_plot = figure(plot_width=750)
#circle_plot.circle(x = 'x_values', y = 'y_values', size='size', color = factor_cmap('circle_color', palette=Spectral3, factors=['0.', '-1.','1.']), source=source)
circle_plot.circle(x = 'x_values', y = 'y_values', size='size', color = factor_cmap('circle_color', palette=['red','green','blue'], factors=['0.0', '-1.0','1.0']), legend = 'circle_color', source=source)
#circle_plot.circle(x = 'x_values', y = 'y_values', source=source)

show(circle_plot)


Loading BokehJS ...

Make plots to check how good the predictions are.

Plot made from the predicted values shows that most of the times the model isn't extremely sure which way the price would shift on the next day. But when it *is* sure, it does predict the right target class most of the times. Most importantly, it almost never misses large price movements.